server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1ea7f05331a9bbed57ec0ea7087d8f2a
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - talk_message
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/ringdong?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 2875drDR
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 초기에는 update → 이후 운영은 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ringdong-secret-key
  expiration: 3600000000 # 임시로 늘림
