server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

app:
  oauth2:
    front-uri: https://ringdong.kr

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1ea7f05331a9bbed57ec0ea7087d8f2a
            client-secret:
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - talk_message
          naver:
            client-id: mgFujTvPvlY3lcdDTch7
            client-secret: dnouDj_f7i
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
          google:
            client-id: 285365440369-opvu0s5nlt5lctvmoti6nhocsb74vdmi.apps.googleusercontent.com
            client-secret: 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
            client-name: Google
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  datasource:
    url: jdbc:mysql://ringdongdb.crya6wgists4.ap-northeast-2.rds.amazonaws.com:3306/ringdongdb
    username: admin
    password: dkaghrkdehaodnrkdgka88
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

sendgrid:
  api-key: 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

jwt:
  secret: ringdong-secret-key
  expiration: 3600000000 # 임시로 늘림
